package com.codesungrape.hmcts.bookapi.service;

import com.codesungrape.hmcts.bookapi.dto.BookRequest;
import com.codesungrape.hmcts.bookapi.entity.Book;
import com.codesungrape.hmcts.bookapi.repository.BookRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

/**
 * Service layer responsible for all business logic related to the Book resource.
 */
@Service
@RequiredArgsConstructor // Lombok creates constructor for dependency injection
public class BookService {

  // Create a field to store the repo
  private final BookRepository bookRepository;

  /**
   * Creates a new Book entity from the given BookRequest DTO and persists it.
   *
   * @param request DTO containing book details (title, author, synopsis)
   * @return The saved Book entity
   * @throws NullPointerException if request is null
   * @throws IllegalArgumentException if title is null or blank
   * @throws IllegalStateException if the repository fails to save the book
   */

  public Book createBook(BookRequest request) {
    // Validation check for business rules (e.g., uniqueness, if required)
    if (request == null) {
      throw new NullPointerException("BookRequest cannot be null");
    }


    // TODO: Leaving this here for now as i haven't implemented the Controller Layer yet
    // The service layer is duplicating validation that already exists in the
    // BookRequest DTO with @notblank annotations. Since the DTO has validation
    // constraints, this manual check is redundant when Spring's validation
    // framework is properly configured in the controller layer.
    // Consider removing this duplication or adding a comment explaining
    // why service-level validation is necessary in addition to DTO validation.
    if (request.title() == null || request.title().isBlank()) {
      throw new IllegalArgumentException("Book title cannot be null or blank");
    }

    // Map DTO to Entity
    Book newBook = Book.builder()
        .title(request.title())
        .author(request.author())
        .synopsis(request.synopsis())
        // ID and created_at are auto-generated by JPA/DB
        .build();

    Book savedBook = bookRepository.save(newBook);

    return savedBook;
  }
}